# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hardcover < Formula
  desc "CLI for Hardcover reading tracker"
  homepage "https://github.com/KIRKR101/hardcover-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "3649193280f73a7c8c5e30942e4d9f0eabd3c21a7baec88e057e3bd2cae73a4d"

      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "ad542bba6e912228d40e956947f6b6642eb3e8daa6a93ec39827dc9dd87a3761"

      define_method(:install) do
        bin.install "hardcover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "c445ffeeff8ea98631cf7c2d6d7ce1c6c976cf058c42a939b1b3951ed7b3d7c0"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "ff8f99a9628ec53db281d0748fbef87f9a1cf103232bcabfab53ad804dcd1494"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
  end

  test do
    system "#{bin}/hardcover", "--version"
  end
end
