# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hardcover < Formula
  desc "CLI for Hardcover reading tracker"
  homepage "https://github.com/KIRKR101/hardcover-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "62d370ea00cc6c183530b01daf947bd360252c5889d6f5b709d664f58791c57c"

      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "5c87122641eee7819597f4a8fd04767909cbfd535ef78dc4093a234260f52c6f"

      define_method(:install) do
        bin.install "hardcover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "75543ee94ce13ac4d9c0eb9974483ac6b8779bbe2bfb37e9b0d1e275965ab87b"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.1.0/hardcover-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "939d936548c376139be91b96784558eb25590dd9bee6dba7c420545789287b57"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
  end

  test do
    system "#{bin}/hardcover", "--version"
  end
end
