# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hardcover < Formula
  desc "CLI for Hardcover reading tracker"
  homepage "https://github.com/KIRKR101/hardcover-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.2.0/hardcover-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "af6d17f6f758c3b4731a63ee337bcb6bae18fcf47d75479abbc999223a1ab19c"

      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.2.0/hardcover-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "16f71a5b2f2db80f4bffe4b5371f87369fce41a634f7237cff45069abefe1fec"

      define_method(:install) do
        bin.install "hardcover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.2.0/hardcover-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "69f29e508ac2461c084be71453cf421e7f271218c0be15077101a014f34dda73"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.2.0/hardcover-cli_0.2.0_linux_armv6.tar.gz"
      sha256 "f2d44c89e8ab5b23cbb0889b83c501c9b17357f062b32ebb0950f0eaf367c16f"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KIRKR101/hardcover-cli/releases/download/v0.2.0/hardcover-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "3e37822e5df1abde954a74702adc64d332b99eb1c869a30fc14cff9f97f0c6dc"
      define_method(:install) do
        bin.install "hardcover"
      end
    end
  end

  test do
    system "#{bin}/hardcover", "--version"
  end
end
